version: "3.9"

services:
  mongodb:
    container_name: thc_mongodb
    image: mongo:4.4.3-bionic
    ports:
      - '27017:27017'

  backend:
    container_name: thc_backend
    build: .
    volumes:
      - ./:/usr/app
    ports:
      - '5000:5000'
    env_file:
      - .env
